# Generated by Django 3.2 on 2021-05-18 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='CheckoutAddress',
        ),
    ]
