# Generated by Django 3.2 on 2021-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_address_checkoutaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip_code',
            field=models.CharField(max_length=15),
        ),
    ]
